In [2]:
import torch
torch.__version__

'2.5.1+cpu'

In [2]:
if torch.cuda.is_available():
    print('Gpu device is', torch.cuda.get_device_name(0))
else:
    print('No GPU available')

No GPU available


## Creating tensors

In [3]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.tensor([[1,2,4], [423,534,6]])

tensor([[  1,   2,   4],
        [423, 534,   6]])

- Each time torch.rand will generate random numbers 

In [3]:
torch.rand(2,4)

tensor([[0.5240, 0.7149, 0.4498, 0.7268],
        [0.5195, 0.8422, 0.7920, 0.5739]])

- To generate same numbers we give the seed value

In [7]:
torch.manual_seed(32)
torch.rand(2,2)

tensor([[0.8757, 0.2721],
        [0.4141, 0.7857]])

- Creating tensors using same functions that we have in numpy

In [10]:
torch.arange(1,99,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [15]:
torch.linspace(2,13,4)

tensor([ 2.0000,  5.6667,  9.3333, 13.0000])

In [16]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
torch.full((3,5),6)

tensor([[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]])

### Shapes in Tensor

In [31]:
a = torch.tensor([[4,53,5434], [4, 534, 64]], dtype=torch.float64)
a

tensor([[4.0000e+00, 5.3000e+01, 5.4340e+03],
        [4.0000e+00, 5.3400e+02, 6.4000e+01]], dtype=torch.float64)

In [32]:
a.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [34]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [36]:
# It works only if we have float elements in our tensor
torch.rand_like(a)

tensor([[0.4556, 0.7414, 0.9739],
        [0.9414, 0.3172, 0.6292]], dtype=torch.float64)

### Dtypes in tensor

In [37]:
a.dtype

torch.float64

In [41]:
# we can even specify the dtype while creating the tensor
torch.ones([2,4], dtype = torch.int32)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

- Converting the dtypes of the tensors

In [44]:
a.to(torch.float32)

tensor([[4.0000e+00, 5.3000e+01, 5.4340e+03],
        [4.0000e+00, 5.3400e+02, 6.4000e+01]])

In [46]:
a.to(torch.int32)

tensor([[   4,   53, 5434],
        [   4,  534,   64]], dtype=torch.int32)

### Mathematical Operation on Tensor

In [47]:
a + 4

tensor([[   8.,   57., 5438.],
        [   8.,  538.,   68.]], dtype=torch.float64)

In [48]:
a -3

tensor([[1.0000e+00, 5.0000e+01, 5.4310e+03],
        [1.0000e+00, 5.3100e+02, 6.1000e+01]], dtype=torch.float64)

In [49]:
a //4

tensor([[1.0000e+00, 1.3000e+01, 1.3580e+03],
        [1.0000e+00, 1.3300e+02, 1.6000e+01]], dtype=torch.float64)

In [50]:
a * 3

tensor([[1.2000e+01, 1.5900e+02, 1.6302e+04],
        [1.2000e+01, 1.6020e+03, 1.9200e+02]], dtype=torch.float64)

In [51]:
a ** 2

tensor([[1.6000e+01, 2.8090e+03, 2.9528e+07],
        [1.6000e+01, 2.8516e+05, 4.0960e+03]], dtype=torch.float64)

### Element wise Operation

In [53]:
b = torch.tensor([1,4,5])
c = torch.tensor([5,6,6])

In [54]:
b + c

tensor([ 6, 10, 11])

In [55]:
b - c

tensor([-4, -2, -1])

In [56]:
d = torch.tensor([4,-2,5,0])

In [59]:
d.abs()

tensor([4, 2, 5, 0])

In [62]:
d.neg()

tensor([-4,  2, -5,  0])

In [69]:
d = torch.randint(size = (2,4), low = 0 ,high=33)

In [71]:
d

tensor([[10, 15,  2,  7],
        [30, 28, 23,  3]])

In [70]:
d.sum()

tensor(118)

In [73]:
d.sum(dim=1)

tensor([34, 84])

In [74]:
d.sum(dim=0)

tensor([40, 43, 25, 10])

In [75]:
d.max()

tensor(30)

In [76]:
d.median()

tensor(10)

### Matrix Operation

In [78]:
e = torch.randint(size=(4,3), low = 0, high=10)
f = torch.randint(size=(3,4), low=2, high = 8)

In [79]:
e 

tensor([[0, 1, 6],
        [6, 5, 8],
        [5, 6, 9],
        [1, 0, 5]])

In [80]:
f

tensor([[4, 7, 5, 7],
        [7, 7, 7, 5],
        [6, 2, 3, 5]])

In [81]:
e.matmul(f)

tensor([[ 43,  19,  25,  35],
        [107,  93,  89, 107],
        [116,  95,  94, 110],
        [ 34,  17,  20,  32]])

In [88]:
e.transpose(1,0)

tensor([[0, 6, 5, 1],
        [1, 5, 6, 0],
        [6, 8, 9, 5]])

In [90]:
# determinant should be of equal row and column matrices
e.det()

RuntimeError: linalg.det: A must be batches of square matrices, but they are 4 by 3 matrices

### Copying a tensor

- Copy a tensor like this in this way if we change our main tensor then there is no effect on other

In [91]:
g = e.clone()

In [92]:
g

tensor([[0, 1, 6],
        [6, 5, 8],
        [5, 6, 9],
        [1, 0, 5]])

- We can see that they are being stored at different address

In [93]:
id(e)

2018049198192

In [94]:
id(g)

2018046762896