In [2]:
import torch
torch.__version__

'2.5.1+cpu'

In [2]:
if torch.cuda.is_available():
    print('Gpu device is', torch.cuda.get_device_name(0))
else:
    print('No GPU available')

No GPU available


## Creating tensors

In [3]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.tensor([[1,2,4], [423,534,6]])

tensor([[  1,   2,   4],
        [423, 534,   6]])

- Each time torch.rand will generate random numbers 

In [3]:
torch.rand(2,4)

tensor([[0.5240, 0.7149, 0.4498, 0.7268],
        [0.5195, 0.8422, 0.7920, 0.5739]])

- To generate same numbers we give the seed value

In [7]:
torch.manual_seed(32)
torch.rand(2,2)

tensor([[0.8757, 0.2721],
        [0.4141, 0.7857]])

- Creating tensors using same functions that we have in numpy

In [10]:
torch.arange(1,99,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [15]:
torch.linspace(2,13,4)

tensor([ 2.0000,  5.6667,  9.3333, 13.0000])

In [16]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
torch.full((3,5),6)

tensor([[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]])

### Shapes in Tensor

In [31]:
a = torch.tensor([[4,53,5434], [4, 534, 64]], dtype=torch.float64)
a

tensor([[4.0000e+00, 5.3000e+01, 5.4340e+03],
        [4.0000e+00, 5.3400e+02, 6.4000e+01]], dtype=torch.float64)

In [32]:
a.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [34]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [36]:
# It works only if we have float elements in our tensor
torch.rand_like(a)

tensor([[0.4556, 0.7414, 0.9739],
        [0.9414, 0.3172, 0.6292]], dtype=torch.float64)

### Dtypes in tensor