In [1]:
import torch
torch.__version__

'2.5.1+cpu'

In [2]:
if torch.cuda.is_available():
    print('Gpu device is', torch.cuda.get_device_name(0))
else:
    print('No GPU available')

No GPU available


## Creating tensors

In [3]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.tensor([[1,2,4], [423,534,6]])

tensor([[  1,   2,   4],
        [423, 534,   6]])